configName: pic32mz_ef_curiosity_v2_winc1500
folderName: pic32mz_ef_curiosity_v2_winc1500
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MZ2048EFM144
projectName: pic32mz_ef_curiosity_v2_winc1500
settings:
  PackageFilter: aws_cloud;bsp;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;net;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.57\atdf\PIC32MZ2048EFM144.atdf
