format_version: v1.0
type: UniqueComponent
attributes: {id: AmazonHWInterface}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: AWS_CLOUD_FREERTOS_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '120000'}
  - type: Integer
    attributes: {id: AWS_CLOUD_SHADOW_UC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Combo
    attributes: {id: AWS_DEMO_RUN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SHADOW}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: AmazonHWInterface}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: AmazonFreeRTOS}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: AmazonHWInterface}
- type: ElementPosition
  attributes: {x: '395', y: '309', id: AmazonHWInterface}
