configName: sam_e70_xult_winc1500
folderName: sam_e70_xult_winc1500
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAME70Q21B
projectName: sam_e70_xult_winc1500
settings:
  PackageFilter: aws_cloud;bsp;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;net;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.3.73\same70b\atdf\ATSAME70Q21B.atdf
